FROM debian:13-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --no-install-recommends --assume-yes dpkg-dev gzip && apt-get clean

VOLUME /root/repo

CMD cd /root/repo && dpkg-scanpackages shinken-deps | gzip -c9 > Packages.gz
